version: '3.3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - app
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    links:
      - app  

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus  
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
    ports:
      - 3001:3000
    links:
      - prometheus

  app:
    image: node:14-alpine
    container_name: app
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: npm run start
    environment:
      NODE_ENV: dev
      PORT: 3000


volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local  