global:
  scrape_interval: 30s
  scrape_timeout: 15s
  evaluation_interval: 1m

scrape_configs:
  - job_name: "app_reports"
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets: ['app:3000']